# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 11:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0048_auto_20160104_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazione',
            name='modulo',
            field=models.CharField(default=b'4,4,2', max_length=5, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
