# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def crea_competizioni(apps, schema_editor):
    IncontroLega = apps.get_model("fantaapp", "IncontroLega")
    Lega = apps.get_model("fantaapp", "Lega")
    IncontroCoppa = apps.get_model("fantaapp", "IncontroCoppa")
    for lega in Lega.objects.all():
        if not lega.competizione_set.exists():
		campionato = lega.competizione_set.create(nome='Campionato')
		coppa = lega.competizione_set.create(nome='Coppa a eliminazione diretta')
    for inc in IncontroLega.objects.all():
		if inc.lega:
			inc.competizione = inc.lega.competizione_set.get(nome='Campionato')
			inc.save()
    for inc in IncontroCoppa.objects.all():
		inc.competizione = inc.lega.competizione_set.get(nome='Coppa a eliminazione diretta')
		inc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0049_auto_20160810_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrizione', models.TextField(blank=True)),
                ('istr', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lega',
            name='con_coppa',
        ),
        migrations.AddField(
            model_name='competizione',
            name='lega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaapp.Lega'),
        ),
        migrations.AddField(
            model_name='incontrocoppa',
            name='competizione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantaapp.Competizione'),
        ),
        migrations.AddField(
            model_name='incontrolega',
            name='competizione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantaapp.Competizione'),
        ),
        migrations.AlterUniqueTogether(
            name='incontrocoppa',
            unique_together=set([('competizione', 'indice', 'tipo')]),
        ),
	migrations.RunPython(crea_competizioni),
        migrations.RemoveField(
            model_name='incontrocoppa',
            name='lega',
        ),
        migrations.RemoveField(
            model_name='incontrolega',
            name='lega',
        ),
    ]
