# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0051_auto_20160815_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calciatore',
            name='ammonizioni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calciatore',
            name='assist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calciatore',
            name='espulsioni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calciatore',
            name='golfatti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calciatore',
            name='golsubiti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calciatore',
            name='presenze',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calciatore',
            name='rigoriparati',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
