# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0052_auto_20160818_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calciatore',
            name='imageurl',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
