# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0053_auto_20160818_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseCompetizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('competizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaapp.Competizione')),
            ],
        ),
    ]
