# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0054_fasecompetizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='incontrocoppa',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantaapp.FaseCompetizione'),
        ),
        migrations.AddField(
            model_name='incontrolega',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantaapp.FaseCompetizione'),
        ),
    ]
