# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0056_auto_20160820_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competizione',
            name='istr',
        ),
    ]
