# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0057_remove_competizione_istr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incontrocoppa',
            name='faseoriginale',
        ),
        migrations.RemoveField(
            model_name='incontrolega',
            name='faseoriginale',
        ),
        migrations.AddField(
            model_name='incontrolega',
            name='descrizioneincontri',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incontrolega',
            name='faseoriginalecasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faseoriginalecasa', to='fantaapp.FaseCompetizione'),
        ),
        migrations.AddField(
            model_name='incontrolega',
            name='faseoriginaletrasferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faseoriginaletrasferta', to='fantaapp.FaseCompetizione'),
        ),
    ]
