# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0058_auto_20160820_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremioCompetizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=10)),
                ('allenatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantaapp.Allenatore')),
                ('competizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaapp.Competizione')),
                ('faseoriginale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantaapp.FaseCompetizione')),
            ],
        ),
    ]
