# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0059_premiocompetizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incontrocampionato',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
