# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaapp', '0061_premiocompetizione_giornata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasecompetizione',
            name='descrizione',
            field=models.TextField(default=b"{'vincitore_pareggio': 'classifica'}"),
        ),
    ]
